---
title: 1. Introduction
toc: true
---

## 1.1 About this guide

Statistics is "the science of collecting, analyzing, presenting, and interpreting data" ([Encyclopaedia Britannica, 2023](https://www.britannica.com/science/statistics)). Presentation of data is a key means to support and guide interpretation and subsequent decision making. Techniques exist for effective display. This is what this guide is all about.

Good data visualisation requires appreciation and careful consideration of the technical aspects of data presentation. But it also involves a creative element. Authorial choices are made about the "story" we want to tell, and design decisions are driven by the need to convey that story most effectively to our audience. Software systems use default settings for most graphical elements, however, each visualisation has its own story to tell, and so we must actively consider and choose settings for the visualisation under construction.

This guide covers both aspects of data visualisation: the art and the science. It is written primarily for contributors to [Royal Statistical Society publications](https://rss.org.uk/news-publication/publications/) -- chiefly, [*Significance* magazine](https://academic.oup.com/jrssig), the [*Journal of the Royal Statistical Society Series A*](https://academic.oup.com/jrsssa), and [Real World Data Science](https://realworlddatascience.net/) -- but we hope you will find the information and advice within to be of broad relevance and use to any data visualisation task.

Our overarching aim is to equip you, the reader, with the fundamentals for creating data visualisations that are high quality, readable, effective at conveying information, accurate in display and interpretation, and which fulfil their intended purpose.

We begin with a discussion of why we visualise data, and then set out the core principles of data visualisation. Next, we provide advice on which chart types are most appropriate for different types of data, and then explore the structure of charts and how those structures can be refined to aid readability. Finally, we look at styling charts, both generally and for RSS publications specifically.

In constructing this guide, we draw on many exceptional textbooks, papers, and other resources created by experts in the field. You will find references to these throughout and we encourage you to seek out the original sources if you are motivated to deepen your understanding and appreciation for the art and science of data visualisation.

## 1.2 How to use this guide

We designed this guide to be read from beginning to end, so that each section builds on the foundations of those that came before. If this is your first time reading the guide, we would encourage you to read it in this way. However, those looking for guidance on specific aspects of data visualisation can make use of the in-built search and navigation functions of this website. If you'd prefer to read offline, you can download a PDF version of the complete guide.

Throughout the text you will find examples of charts and graphs. For many of these, we provide code in R to allow you to reproduce the visualisations, and we encourage you to do so and to adapt the code for your own purposes.

## 1.3 How to contribute to this guide

\[add section on how to contribute using GitHub repo, etc., once set up\]

## 1.4 How to engage with other users of this guide

\[add section on using GitHub discussions. Could also consider adding a comment functionality to section pages. Also need to include guidance on standards of discourse - e.g. be civil, no libellous comments, etc.\]

## 1.5 Copyright, re-use, distribution, and disclaimer

This guide is copyright © 2023 Andreas Krause, Nicola Rennie and the Royal Statistical Society. Unless otherwise stated, all copyright content in this guide is licensed under a [Creative Commons Attribution 4.0 (CC BY 4.0) International licence](http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1), meaning it can be used and adapted for any purpose, provided attribution is given to the original authors. **How to cite:** Authors, Title, Version, URL.

If you've found this guide useful and want to make use of it or build on it for other purposes, please do so -- and please share your work with us.

No warranty, use at your own risk, etc. See the R disclaimer for an example ("R comes with absolutely no warranty").

## 1.6 How to reach us

How can readers contact the authors?

-   Submit a GitHub issue

-   Email address?
