---
title: 6. Styling your charts
format:
  html:
    code-fold: true
    code-tools: true
execute: 
  eval: false
  echo: true
---


## Principles of styling charts

The two charts below show the same data using the same type of chart - guinea pig tooth growth data visualised on a horizontal bar chart. However, the clarity of the two charts is distinctly different. The choice of colours, addition of text annotations, change of font size, and more informative labels make the chart on the right hand side much easier to interpret. In this section, we’ll explore each of these elements in detail, and discuss how to style different elements of charts to improve accessibility and interpretability of your data visualisations.

## Fonts

Font choice is a key component of making your data visualisations easy to understand. Some fonts are easier to read than others, and this is particularly true for those with visual impairments, or a learning disability such as dyslexia. A poor choice of font may make your visualisation inaccessible to a significant number of people in your audience. 

Try to minimise the number of different types of font you use: use a fixed set of sizes, a maximum of two different font families, and minimise the use of mixing font faces. This all helps to reduce unnecessary work from a reader when they look at your visualisation.

### Font size

Larger fonts are easier to read. It’s generally recommended that font size is at least 12pt for printed materials or websites. If you’re creating a presentation, fonts should be at least 36pt to make sure they’re visible to people nearer the back of the room.

### Font family

So what makes a good choice of font family? There is no consensus as to which type of font (serif, sans serif, or monospace) is more accessible. The simpler characters of sans serif fonts may increase readability for visually impaired readers, while those with dyslexia may find the characters more difficult to tell apart. Serif fonts (such as Times New Roman) can be more difficult to read as the decorative lines distract from the shape of the letter. This is especially true in digital publications where on-screen pixelation can further distort the letters. We’d recommend avoiding serif fonts for any text in images that will appear online.

Common sans serif fonts such as Arial, Calibri, and Verdana are often considered to be accessible. Dyslexie and OpenDyslexic are fonts specifically designed to aid readability for those with dyslexia, as they increase font weight at the bottom of the letters which reduces how much the letters appear to move around. Atkinson Hyperlegible is a font developed by the Braille Institute of America, which is designed to maximise distinction between different characters for low vision readers . It’s freely available, and can be downloaded from the Braille Institute or used through Google Fonts. Some fonts, particularly sans serif fonts, have characters which appear very similar to other characters. For example, a capital I, lowercase l, and number 1, can sometimes be indistinguishable. Choose a font face with a distinguishable feature for each letter and number.

### Font face

Font faces, e.g. bold or italic effects can be used to emphasise particular parts of text. For example, a plot annotation may highlight a specific value placed in amongst some explanatory text. Italicised text is generally considered more difficult to read, as is capitalised text when used for the purpose of emphasis. Instead, use bold text to highlight (sparingly).

### Checklist

As you can see, there is no single font recommendation that will ensure your visualisation is accessible to all. However, there are some things you can do to maximise accessibility.

* Ensure the font size is at least 12pt.
* Ensure that a capital I, lowercase l, and number 1 are distinguishable. 
* Minimise the number of different fonts used (no more than two).
* Minimise the use of italics and uppercase text, instead (sparingly) use bold text for emphasis.

## Colours

As with font choices, colour choices can strongly impact the accessibility of your data visualisation. The correct use of colour can also help to emphasise the story you are trying to tell.

Before you get into choosing colours, ask yourself the question: do I really need to use colour here? Beecham et al showed that the use of colour is one of the least effective methods for visually communicating differences between variables. Both accessibility and interpretability improve when using fewer colours. 

In the bar chart example above, rather than duplicating the information on the y-axis and colouring each bar a different colour, a better approach is to use colour to highlight a specific element of the data e.g. a specific car, which focuses the reader’s attention straight to the point you are trying to make.

It’s useful not to rely on colour as the only factor which distinguishes data points in different groups. For example, in scatter plots, as well as colouring points in two groups either green or orange, the points code be encoded as circles and triangles.

Despite the difficulties that can arise from ineffectively using colour, it’s still one of the most common methods for either distinguishing between categories, or showing changes in a value. When you decide to use colours, you then need to decide which colours to use.

### Types of colour palette

Colour palettes generally fall into one of three categories, and the type of colour palette you choose should reflect the type of data you are visualising.

* **Sequential**: used to visualise data that is ordered from low to high (or vice versa) e.g. temperature.
* **Diverging**: used to visualise data that is ordered and diverges from an important midpoint e.g. days of above or below average temperature.
* **Qualitative**: used to visualise categorical data, where the magnitude of difference between, and ordering of, categories is not important e.g. distinct railway lines.

### Accessible colour palettes
When choosing a particular colour palette, there are several important factors to consider:

Colours should be distinct from each other, for all readers. There are several different forms of colour blindness which can cause some colours to appear indistinguishable. The use of a colour blind checker can show you what your plots may look like under different types of colour blindness. This is particularly important for diverging and qualitative palettes where the distinction between hues is used to tell apart different values. In contrast, sequential palettes often use luminosity to show how values change. Paul Tol has some very useful resources on choices of colours, and several suggested palettes.


Colours should appear distinct from each other when printed in black and white. Readers, or indeed academic journals, may choose to print your visualisations in monochrome. Colours that seem visually distinct that have similar luminosity (a measure of how light or dark a hue is) may appear indistinguishable when printed in black and white.

Colours should appropriately match your data. It’s important not to play into stereotypes e.g. choosing pink and blue for data relating to women and men. Don’t confuse your readers by flipping common colour associations around, e.g. red for good and green for bad. Lisa Muth wrote an article for Datawrapper discussing the use of colour to display gender data, and many of the points can be extended to other types of data.

### Checklist
* Minimise the number of different colours used.
* Check that your colours are colour blind friendly, and have sufficient contrast when viewed in monochrome.
* Check that the type of colour palette matches the type of data visualised.
* Use non-colour elements to distinguish between different groups where possible.
* Avoid stereotypes and confusing associations with different colours.

## Annotations

When talking about adding annotations to data visualisations, we simply mean adding text that adds a comment or clarification in order to help the reader understand the point made in the graphic. Annotations can be used to add details or explanation, highlight an interesting data point, or clarify how the chart should be interpreted. Although additional text can be extremely useful to a reader, it’s important not to overload a data visualisation with text as it can be distracting and make it more difficult to focus the point. 

A common use of annotation that enhances clarity of data visualisations is directly labelling data points on line graphs or bar charts. In line graphs, it’s common to label the value at the end of the line as it’s often far away from the y-axis labels (on the left by default). In bar charts, adding the values for each bar at, or near, the end of each bar also means readers don’t have to look up the values themselves. This can reduce the amount of eye movement required for readers to find the exact values and allows them to make better, more accurate comparisons. This isn’t always required if, for example, these values are additionally provided in a table.

The placement of annotations is also key:

* In a scatter plot, directly labelling every data point isn’t usually an option as there are too many points to label without clutter. Instead, you may choose to highlight only one or two interesting points, such as outliers.
* When adding more extensive text to explain an outlier or point of interest, place the text in a relevant position. For example, if you’re annotating a line chart to explain a decrease in value in 2008 - position the text near to 2008.
* Don’t fill every white space with text. The ONS recommends a maximum of 3 or 4 annotations per chart to avoid overwhelming readers. This also means keeping annotations brief and to the point. This is especially true for data visualisations that accompany journal publications or magazine articles where further textual explanation is likely included already.

When choosing the font size, family, face, and colour of the annotation text, the same advice applies as given in the previous sections. It’s particularly important to check there is sufficient contrast between the background colour and the text colour.

### Checklist

* Check if there are outliers that need further explanation, or values that could be directly labelled.
* Labels are positioned sensibly, and the data visualisation does not feel crowded with text.
* Make sure there is sufficient contrast between the text and the background.


